services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
    volumes:
      - ./data/db1:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tennis
      - MONGO_REPLICA_SET_NAME=rs0
      - MONGO_PORT=27017
      - MONGO_PRIORITY=1
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]

  mongodb2:
    image: mongo:latest
    depends_on:
      - mongodb1
    container_name: mongodb2
    ports:
      - "27018:27017"
    volumes:
      - ./data/db2:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tennis
      - MONGO_REPLICA_SET_NAME=rs0
      - MONGO_PORT=27017
      - MONGO_PRIORITY=0
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]

  mongodb3:
    image: mongo:latest
    depends_on:
      - mongodb2
    container_name: mongodb3
    ports:
      - "27019:27017"
    volumes:
      - ./data/db3:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tennis
      - MONGO_REPLICA_SET_NAME=rs0
      - MONGO_PORT=27017
      - MONGO_PRIORITY=0
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]

  mongo-init-replica:
    image: mongo:latest
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    volumes:
      - ./scripts:/scripts
    command:
      [
        "mongosh",
        "mongodb://mongodb1:27017/admin",
        "/scripts/init-replica.js"
      ]

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

