secrets:
  mongodb_uri:
    file: ./secrets/mongodb_uri.txt
  redis_address:
    file: ./secrets/redis_address.txt
  redis_password:
    file: ./secrets/redis_password.txt
  grafana_graphite_token:
    file: ./secrets/grafana_graphite_token.txt
