version: '3.7'

services:
  categories:
    build: ./categories
    container_name: categories
    image: neniel/tennis-categories:latest
    ports:
      - 8080:8080
    environment:
      - APP_PORT=:8080
      - APP_ENVIRONMENT=docker
      - CONFIG_FILE=/run/secrets/config
    secrets:
      - config

  players:
    build: ./players
    container_name: players
    image: neniel/tennis-players:latest
    ports:
      - 8081:8080
    environment:
      - APP_PORT=:8080
      - APP_ENVIRONMENT=docker
      - CONFIG_FILE=/run/secrets/config
    secrets:
      - config

  tournaments:
    build: ./tournaments
    container_name: tournaments
    image: neniel/tennis-tournaments:latest
    ports:
      - 8082:8080
    environment:
      - APP_PORT=:8080
      - APP_ENVIRONMENT=docker
      - CONFIG_FILE=/run/secrets/config
    secrets:
      - config

  tenants:
    build: ./tenants
    container_name: tenants
    image: neniel/tennis-tenants:latest
    ports:
      - 8083:8080
    environment:
      - APP_PORT=:8080
      - APP_ENVIRONMENT=docker
      - CONFIG_FILE=/run/secrets/config
    secrets:
      - config

  #cache:
  #  build: ./cache
  #  container_name: cache
  #  image: neniel/tennis-cache:latest
  #  environment:
  #    - APP_ENVIRONMENT=docker
  #    - CONFIG_FILE=/run/secrets/config
  #  secrets:
  #    - config

secrets:
  config:
    file: ./secrets/config.json

