services:
  categories:
    build: ./categories
    container_name: categories
    ports:
      - 8080:8080
    environment:
      - APP_PORT=:8080
      - APP_ENVIRONMENT=docker
      - MONGODB_URI_FILE=/run/secrets/mongodb_uri
      - REDIS_ADDRESS_FILE=/run/secrets/redis_address
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
      - GRAFANA_GRAPHITE_TOKEN=/run/secrets/grafana_graphite_token
    secrets:
      - mongodb_uri
      - redis_address
      - redis_password
      - grafana_graphite_token

  players:
    build: ./players
    container_name: players
    ports:
      - 8081:8080
    environment:
      - APP_PORT=:8080
      - APP_ENVIRONMENT=docker
      - MONGODB_URI_FILE=/run/secrets/mongodb_uri
      - REDIS_ADDRESS_FILE=/run/secrets/redis_address
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
      - GRAFANA_GRAPHITE_TOKEN=/run/secrets/grafana_graphite_token
    secrets:
      - mongodb_uri
      - redis_address
      - redis_password

  cache:
    build: ./cache
    container_name: cache
    environment:
      - APP_ENVIRONMENT=docker
      - MONGODB_URI_FILE=/run/secrets/mongodb_uri
      - REDIS_ADDRESS_FILE=/run/secrets/redis_address
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
      - GRAFANA_GRAPHITE_TOKEN=/run/secrets/grafana_graphite_token
    secrets:
      - mongodb_uri
      - redis_address
      - redis_password

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
