services:
  categories:
    build: ./categories
    container_name: categories
    image: neniel/tennis-categories:latest
    ports:
      - 8080:8080
    environment:
      - APP_PORT=:8080
      - APP_ENVIRONMENT=docker
      - CONFIG_FILE=/run/secrets/config
    secrets:
      - config

  players:
    build: ./players
    container_name: players
    image: neniel/tennis-players:latest
    ports:
      - 8081:8080
    environment:
      - APP_PORT=:8080
      - APP_ENVIRONMENT=docker
      - CONFIG_FILE=/run/secrets/config
    secrets:
      - config

  cache:
    build: ./cache
    container_name: cache
    image: neniel/tennis-cache:latest
    environment:
      - APP_ENVIRONMENT=docker
      - CONFIG_FILE=/run/secrets/config
    secrets:
      - config

include:
  - docker-compose-secrets.yml
