version: '3.7'

services:
  categories:
    build: ./categories
    container_name: categories
    image: neniel/tennis-categories:latest
    ports:
      - 8080:443
    environment:
      - APP_PORT=:443
      - APP_ENVIRONMENT=docker
      - LOGGING_LEVEL=DEBUG
      - CONFIG_FILE=/run/secrets/config
    secrets:
      - config

  players:
    build: ./players
    container_name: players
    image: neniel/tennis-players:latest
    ports:
      - 8081:443
    environment:
      - APP_PORT=:443
      - APP_ENVIRONMENT=docker
      - LOGGING_LEVEL=DEBUG
      - CONFIG_FILE=/run/secrets/config
    secrets:
      - config

  tournaments:
    build: ./tournaments
    container_name: tournaments
    image: neniel/tennis-tournaments:latest
    ports:
      - 8082:443
    environment:
      - APP_PORT=:443
      - APP_ENVIRONMENT=docker
      - LOGGING_LEVEL=DEBUG
      - CONFIG_FILE=/run/secrets/config
    secrets:
      - config

  tenants:
    build: ./tenants
    container_name: tenants
    image: neniel/tennis-tenants:latest
    ports:
      - 8083:443
    environment:
      - APP_PORT=:443
      - APP_ENVIRONMENT=docker
      - LOGGING_LEVEL=DEBUG
      - CONFIG_FILE=/run/secrets/config
    secrets:
      - config

  auth:
    build: ./auth
    container_name: auth
    image: neniel/tennis-auth:latest
    ports:
      - 8084:443
    volumes:
      - ./localhost.crt:/tmp/localhost.crt
      - ./localhost.key:/tmp/localhost.key
    environment:
      - APP_ENVIRONMENT=docker
      - LOGGING_LEVEL=DEBUG
      - CONFIG_FILE=/run/secrets/config
      - CERTIFICATE_PATH=/tmp/localhost.crt
      - KEY_PATH=/tmp/localhost.key
    secrets:
      - config

  #cache:
  #  build: ./cache
  #  container_name: cache
  #  image: neniel/tennis-cache:latest
  #  environment:
  #    - APP_ENVIRONMENT=docker
  #    - CONFIG_FILE=/run/secrets/config
  #  secrets:
  #    - config

secrets:
  config:
    file: ./secrets/config.json

volumes:
  ca-certificate:
    driver: local
    driver_opts:
      type: none
      device: ca.crt
      o: bind
