apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.app.namespace }}
  name: categories-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.app.categories.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.categories.name }}
    spec:
      containers:
      - name: {{ .Values.app.containers.categories.name }}
        image: "{{ .Values.app.images.categories.name }}:{{ .Values.app.images.categories.tag }}"
        ports:
        - containerPort: {{ .Values.app.containers.categories.port }}
        env:
        - name: APP_PORT
          value: :{{ .Values.app.containers.categories.port }}
        - name: APP_ENVIRONMENT
          value: k8s
        - name: CONFIG_FILE
          valueFrom:
            secretKeyRef:
              name: tennis-secret
              key: config
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.app.namespace }}
  name: {{ .Values.app.services.categories.name }}
spec:
  #type: LoadBalancer
  selector:
    app: {{ .Values.app.categories.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.services.categories.port }}
      targetPort: {{ .Values.app.services.categories.targetPort }}
