apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
  namespace: {{ .Values.app.namespace }}
spec:
  rules:
  - host: "categories.tennis.dev"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.app.services.categories.name }}
            port:
              number: {{ .Values.app.services.categories.port }}
  - host: "players.tennis.dev"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.app.services.players.name }}
            port:
              number: {{ .Values.app.services.players.port }}
