apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
  namespace: {{ .Values.app.namespace }}
spec:
  tls:
  - hosts:
    - api.tennis.dev
    secretName: tls-secret
  rules:
  - http:
    paths:
      - path: "/api/categories"
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.services.categories.name }}
            port:
              number: {{ .Values.app.services.categories.port }}
      - path: "/api/players"
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.services.players.name }}
            port:
              number: {{ .Values.app.services.players.port }}
