apiVersion: v1
kind: Secret
metadata:
  name: tennis-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  mongodb_connection_string: {{ .Values.app.secrets.mongodb_connection_string }}
  redis_server_address: {{ .Values.app.secrets.redis_server_address }}
  redis_password: {{ .Values.app.secrets.redis_password }}
  grafana_graphite_token: {{ .Values.app.secrets.grafana_graphite_token }}
