apiVersion: v1
kind: Secret
metadata:
  name: application-secret
type: Opaque
data:
  mongodb_connection_string: bW9uZ29kYjovL21vbmdvOjI3MDE3L3Rlbm5pcwo=
  redis_server_address: cmVkaXM6NjM3OQo=
  redis_password: Cg==
  grafana_graphite_token: Z2xjX2V5SnZJam9pTnprNU56QXhJaXdpYmlJNkluTjBZV05yTFRrek16UTNNeTFwYm5SbFozSmhkR2x2YmkxMFpYTjBOQ0lzSW1zaU9pSTJOMU16T0UwM00wRXhiMHBzUVVaaE9ERnphVGRXVkhraUxDSnRJanA3SW5JaU9pSndjbTlrTFhWekxXVmhjM1F0TUNKOWZRPT0K

