apiVersion: v1
kind: Secret
metadata:
  name: mongodb-connection-string-secret
type: Opaque
data:
  mongodb_connection_string: bW9uZ29kYjovL21vbmdvOjI3MDE3L3Rlbm5pcwo=

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-server-address-secret
type: Opaque
data:
  redis_server_address: cmVkaXM6NjM3OQo=

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-password-secret
type: Opaque
data:
  redis_password: Cg==

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-graphite-token-secret
type: Opaque
data:
  grafana_graphite_token: QmVhcmVyIDE1ODI2MzQ6Z2xjX2V5SnZJam9pTnprNU56QXhJaXdpYmlJNkluTjBZV05yTFRrek16UTNNeTFwYm5SbFozSmhkR2x2YmkxMGIydGxiak1pTENKcklqb2ljek5qTUhKNk5XODNhMmgyZWpZM09UTlNRWEl6T0VwUElpd2liU0k2ZXlKeUlqb2ljSEp2WkMxMWN5MWxZWE4wTFRBaWZYMD0K

